### PR TITLE
Non-Returnable Repor - pdf formatting

### PR DESCRIPTION
**Pull request by jgwaltney-gsa**

### CODE REVIEW

**Comment by wdinkel** [comment]
Any way to include all rows in the resulting pdf, without having to show all rows in the grid first? We currently can't do that in the grid, because the options for row-per-page are 5, 10, 20.
As for the row-per-page, the dropdown seems to be covering up the "items per page" label. Can we adjust that?

**Comment by jgwaltney-gsa** [comment]
I will look into this, and see if there is a way to manipulate that.

**Comment by jgwaltney-gsa** [comment]
See latest. fixed label overlap and now exports all pages of grid as one pdf.

**Comment by wdinkel** [comment]
That seems to have done the trick! A couple additional notes:

- The "Report Title required" validation div doesn't seem to be vertically aligned with the dropdown. It's a little lower.
- The "Export PDF" button still tries to generate a pdf even if the dropdown and date field aren't populated. Can you add validation to that button action?
- Clicking "Export PDF" before clicking "Generate" seems to have some issues with an incomplete header in the resulting pdf. It looks like some of the dynamic text in the header doesn't get populated before export.
- Should clicking "Clear" also clear the grid, or just the input fields? This may require some discussion, as the existing app doesn't have a grid.

**Comment by jgwaltney-gsa** [comment]
Sure thing, will address these.

**Comment by jgwaltney-gsa** [comment]
All updates made:

DONE => Clicking "Export PDF" before clicking "Generate" seems to have some issues with an incomplete header in the resulting pdf. 
It looks like some of the dynamic text in the header doesn't get populated before export.

DONE - The "Export PDF" button still tries to generate a pdf even if the dropdown and date field aren't populated. Can you add validation to that button action?

DONE The "Report Title required" validation div doesn't seem to be vertically aligned with the dropdown. It's a little lower.

DONE - Should clicking "Clear" also clear the grid, or just the input fields? This may require some discussion, as the existing app doesn't have a grid.

DONE - can you take the "RECON-NWTB" text out of the report page header? Since it's already up above on the menu.

**Comment by wdinkel** [comment]
Merged latest master. Branch looks good. Approving PR.

**Pull request merged**
